### PR TITLE
Update repos-github.md

### PR DESCRIPTION
**Pull request by pawelprazak**
Add VirtusLab/besom to repos-github.md

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @tgodzik ?

**Comment by tgodzik** [comment]
> review by @tgodzik ?

I haven't merged it because I don't think it will work currently. It uses scala-compose underneath which is just a prototype.

**Comment by pawelprazak** [comment]
> > review by @tgodzik ?
> 
> I haven't merged it because I don't think it will work currently. It uses scala-compose underneath which is just a prototype.

I was wandering if it would be possible to use it as a collection of standalone `scala-cli` projects. 
I've beed using this pattern to force IntelliJ to work properly and it mostly works. 
There's just a lot of BSP connections ;)

**Comment by tgodzik** [comment]
> > > review by @tgodzik ?
> > 
> > 
> > I haven't merged it because I don't think it will work currently. It uses scala-compose underneath which is just a prototype.
> 
> I was wandering if it would be possible to use it as a collection of standalone `scala-cli` projects. I've beed using this pattern to force IntelliJ to work properly and it mostly works. There's just a lot of BSP connections ;)

It should be possible, but I am not sure if Scala Steward supports that use case yet.

**Comment by lbialy** [comment]
We could start with just core sdk maybe and then contribute multi-module capabilities (if not present)?

**Comment by tgodzik** [comment]
I wonder whether would should set up something similar to https://github.com/scalameta/steward for it though. It will be easier to debug.

**Pull request closed without merging**
