### PR TITLE
add s5bug/squirrel-explorer

### PR DESCRIPTION
**Pull request by s5bug**
This adds my own project squirrel-explorer. This is my first time working with Scala Steward, so it would be very much appreciated if someone could check that my config file https://github.com/s5bug/squirrel-explorer/blob/d00938db4ec1ea5ec08b0560284d4d2e5ca9a27a/.github/scala-steward.conf is correct.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]

**Comment by tgodzik** [comment]
> This adds my own project squirrel-explorer. This is my first time working with Scala Steward, so it would be very much appreciated if someone could check that my config file https://github.com/s5bug/squirrel-explorer/blob/d00938db4ec1ea5ec08b0560284d4d2e5ca9a27a/.github/scala-steward.conf is correct.

I think it looks good, though we should see in a couple of days if it works indeed. Steward is run every two days I think

**Comment by s5bug** [comment]
@tgodzik It seems Scala Steward ran yesterday: I feel like it should have made a PR? I currently have out-of-date:
- Scala 3.5.2 to 3.6.2
- cats-effect 3.5.5 to 3.5.7
- calico 0.2.2 to 0.2.3
- jsoniter-scala-core and jsoniter-scala-macros 2.31.1 to 2.32.0 (is there anything special I need to do to make sure these always get upgraded together?)

**Comment by tgodzik** [comment]
I run on 15th, not sure about the exact timeline and it take a long while to run.

We could try debugging it locally to make sure it's working. It's really hard to get the azure logs :sweat:

**Comment by tgodzik** [comment]
https://github.com/scala-steward-org/scala-steward/blob/main/docs/running.md <- if you have time to check it, but I can also do it later

**Comment by s5bug** [comment]
Is there a way to do a "dry run" so I don't have to set up a GitHub account or token or shell script? Like, a way to do an account-less clone and just print out what _would_ be PR'd if auth was provided?

**Comment by s5bug** [comment]
```
[info] 2025-01-05 15:15:59,157 INFO  Configuration file at C:\Users\aprim\Documents\squirrel-explorer\.github\scala-steward.conf is valid.
```

**Comment by s5bug** [comment]
@tgodzik Running locally, it works: it creates the exact PRs I mentioned.
image

**Comment by tgodzik** [comment]
It looks to ok also according to https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

Maybe there is something weird about checkout that steward does. I will try to get the logs for scala steward job today

**Comment by tgodzik** [comment]
```
[error] (externalNpm) java.io.IOException: Cannot run program "pnpm" (in directory "/opt/workspace/repos/s5bug/squirrel-explorer"): error=2, No such file or directory
[error] Total time: 0 s, completed Jan 7, 2025, 3:08:31 PM
```

Looks like it, though I am not sure how to disable it being run.

**Comment by tgodzik** [comment]
We would probably need to change the image like this https://github.com/scala-steward-org/scala-steward/pull/1526

**Comment by s5bug** [comment]
I refuse to pollute the scala-steward image with software that shouldn't even be running in the first place for a dependency updater. I'm looking into how to prevent source generators from running when my project is being evaluated by scala-steward.

**Comment by tgodzik** [comment]
Maybe there is a CI variable that we check for?

**Comment by s5bug** [comment]
Does Scala Steward need to run source generation tasks at all? Maybe it is more correct to have Steward itself run its SBT commands bypassing source generation tasks.

**Comment by tgodzik** [comment]
> Does Scala Steward need to run source generation tasks at all? Maybe it is more correct to have Steward itself run its SBT commands bypassing source generation tasks.

I can't think of a reason it would need to, but there might have been reason why it's being done this way.

**Comment by mzuehlke** [comment]
Steward only reads `libraryDependencies`: https://github.com/scala-steward-org/sbt-plugin/blob/main/modules/sbt-plugin-1_3_11/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_3_11.scala#L40 and is not invoking any source generators.
It seems ST hooks into project loading: https://github.com/ScalablyTyped/Converter/blob/02257bf3588da08deec5a3b07f306fcc6236642d/docs/plugin.md?plain=1#L101-L118

No clue if there is a way to avoid this.

**Comment by tgodzik** [comment]
Might just be easier at this point to just run this on a github action with pnpm installed :thinking:

**Comment by s5bug** [comment]
For now, prepending
```
set every _root_.org.scalablytyped.converter.plugin.ScalablyTypedConverterPlugin.autoImport.stImport := { (null, _root_.org.scalablytyped.converter.internal.ImportTypings.Output(Set.empty, _root_.org.scalablytyped.converter.internal.IArray.Empty)) }
```
to SBT commands prevents PNPM from running, but there honestly should be a way for ScalablyTyped to not run on literally every operation (even `clean` calls PNPM!)

**Comment by fthomas** [comment]
> Maybe there is a CI variable that we check for?

Btw, Scala Steward does not set a specific environment variable by itself, but there is the CLI option [`--env-var`](https://github.com/scala-steward-org/scala-steward/blob/main/docs/help.md) which could be used here. For example, running it with `--env-var SCALA_STEWARD=1` it would set this environment variable for all other processes it runs.

**Comment by tgodzik** [comment]
I've set `SCALA_STEWARD=1` so we should be good to try it out.

**Comment by s5bug** [comment]
I added a check for it: my Scala is out of date (and likely some of my libraries too) so I should receive PRs the next time it runs.

**Comment by s5bug** [comment]
It works! Hooray!!

**Pull request merged**
