### PR TITLE
Update repos-github.md

### PR DESCRIPTION
**Pull request by FLimburg**
added actian's fork of lemonlabsuk/scala-uri to the list

### CODE REVIEW

**Comment by tgodzik** [comment]
Thanks for adding the repo! However, why not add the original repo instead of the fork?

**Comment by FLimburg** [comment]
The original is already present, but at the moment not maintained.

**Comment by tgodzik** [comment]
Ach, this will not work then. We had issue when different forks were present of the same repo. I can delete the Steward fork, which should fix it, but maybe it would be possible to reach out and ask for maintainer status in the original repo? This would make the library be released with the same coordinates and would probably be welcome.

**Comment by Philippus** [comment]
You can also use the GitHub chatbot-virtual-assistant at https://support.github.com/contact?tags=rr-forks&subject=Detach%20Fork&flow=detach_fork to detach the fork from the original.

**Review by tgodzik — APPROVED** [review]
Looks like we can merge it now. @FLimburg do you still need it or did you set up something yourself?

**Comment by FLimburg** [comment]
I was just about to say yes, please go ahead and merge, but it seems by not https://github.com/indoorvivants/scala-uri just started to maintain the scala-uri project

**Pull request merged**
