### PR TITLE
Add `sbt/setup-sbt`

### PR DESCRIPTION
**Pull request by Friendseeker**
@eed3si9n @SethTisue good to go?

Btw I would also want to inquire whether changes are needed at `sbt/setup-sbt` too. I don't know how Scala Steward works but here's the only reference to sbt version in `sbt/setup-sbt`.

```
inputs:
  sbt-runner-version:
    description: "The runner version (The actual version is controlled via project/build.properties)"
    required: true
    default: 1.10.3
```

https://github.com/sbt/setup-sbt/blob/0e649c9d325023db10f4c28603a7870d04c16141/action.yml#L7

Do we need to add a `build.properties` file in `sbt/setup-sbt` for Scala Steward to pick up the sbt version & update `action.yml`?

### CODE REVIEW

**Comment by mzuehlke** [comment]
@Friendseeker Scala Steward gets the sbt version from `project/build.properties`.
See: https://github.com/scala-steward-org/scala-steward/blob/0bc0acba0ace93f4fc40f752170dd187d80d3404/modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala#L50-L54

That version number will then be replaced in all files matching this pattern: https://github.com/scala-steward-org/scala-steward/blob/0bc0acba0ace93f4fc40f752170dd187d80d3404/docs/repo-specific-configuration.md?plain=1#L120

**Review by tgodzik — APPROVED** [review]

**Comment by eed3si9n** [comment]
So here's a pull request I got from the robot today https://github.com/sbt/setup-sbt/pull/15. I don't know the implementation of scala-steward, but I don't see how it would know that the sbt version in `sbt.version=1.10.4` would translate to [YAML](https://github.com/sbt/setup-sbt/blob/main/action.yml)

```yaml
default: 1.10.3
```

**Comment by Friendseeker** [comment]
Guess Scala Steward's algorithm is being overly pessimistic in this case...

Wonder if Scala Steward's algorithm can be improved somehow. If not, I guess I can write a custom bot tailed for `setup-sbt` to automatically submit PR to update its sbt version and remove `setup-sbt` from list of Scala Steward repos.

**Comment by xuwei-k** [comment]
https://github.com/scala-steward-org/scala-steward/blob/9349c67f8f4ecf4fb54dfeceee234d0e2dc9bf8c/modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala#L92-L104

https://github.com/scala-steward-org/scala-steward/blob/9349c67f8f4ecf4fb54dfeceee234d0e2dc9bf8c/docs/repo-specific-configuration.md#L119-L121

🤔

**Comment by eed3si9n** [comment]
https://github.com/scala-steward-org/scala-steward/blob/9349c67f8f4ecf4fb54dfeceee234d0e2dc9bf8c/modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala#L143-L155


```scala
  test("keyword with extra underscore") {
    val update =
      ("org.scala-js".g % Nel.of("sbt-scalajs".a, "scalajs-compiler".a) % "1.1.0" %> "1.1.1").group
    val original = Map(
      ".travis.yml" -> """ - SCALA_JS_VERSION=1.1.0""",
      "project/plugins.sbt" -> """val scalaJsVersion = Option(System.getenv("SCALA_JS_VERSION")).getOrElse("1.1.0")"""
    )
    val expected = Map(
      ".travis.yml" -> """ - SCALA_JS_VERSION=1.1.1""",
      "project/plugins.sbt" -> """val scalaJsVersion = Option(System.getenv("SCALA_JS_VERSION")).getOrElse("1.1.1")"""
    )
    runApplyUpdate(update, original, expected)
  }
```

so I'm guessing that YAML works for `- SCALA_JS_VERSION=1.1.0` type of lists where it builds up environment variable with the artifact name in the variable name?

**Comment by mzuehlke** [comment]
@fthomas could describe this the best as he wrote the replacement algorithm.
But replacements need the artifact name close to the version number.

**Comment by fthomas** [comment]
> But replacements need the artifact name close to the version number.

That's correct. If the field would be called something like `default-sbt-version`, Scala Steward would classify it as candidate for the sbt version. But since there is also a regular `project/build.properties` it prefers updating that over the version in the YAML file.

I think the easiest way to get Scala Steward to update that version is to write a sbt task that replaces the version in the YAML and then use that task in a `postUpdateHook` in a `.scala-steward.conf`:
```
postUpdateHooks = [{
  command = ["sbt", "updateYaml"],
  commitMessage = "Regenerated action.yaml",
  groupId = "org.scala-sbt",
  artifactId = "sbt"
}]
```
On sbt updates, Scala Steward would run `sbt updateYaml` after the update and commit the changes.

**Comment by tgodzik** [comment]
Och, that looks awesome, I wasn't even aware of that config option. Mind if I use your snippet and put it on Scala Space to spread the knowledge a bit?

**Comment by fthomas** [comment]
No, I don't mind.

It is the same mechanism that Scala Steward uses to regenerate GitHub Action workflows for example. Here are the `postUpdateHook`s Scala Steward uses by default:
* https://github.com/scala-steward-org/scala-steward/blob/eae30d0ce47334c04e94dd47410e2992d2c3e5eb/modules/core/src/main/resources/default.scala-steward.conf#L7-L28
* https://github.com/scala-steward-org/scala-steward/blob/eae30d0ce47334c04e94dd47410e2992d2c3e5eb/modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala#L150-L196

**Pull request merged**
