### PR TITLE
Removed Bakery repo update repos-github.md

### PR DESCRIPTION
**Pull request by Tim-Linschoten**
Removed Bakery repo update repos-github.md

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]

**Comment by bekiroguz** [comment]
Hi @tgodzik , may I ask when we can expect the fork of our repo also to be deleted? I thought that process is automated, but the fork repo is still there.

**Comment by tgodzik** [comment]
I am not sure I understand,  which fork? Or do you mean the scala steward fork? In that case it's not automated, but I can remove it.

To automate it would require a feature request to scala steward I think.

**Comment by bekiroguz** [comment]
Yes please. I meant this one: https://github.com/scala-steward/baker
Probably we'll configure scala-steward again at a later stage of our project. But for now it's better for us that fork to be deleted. Thanks in advance.

**Comment by tgodzik** [comment]
Ok, I removed it :+1:

**Pull request merged**
